### ISSUE TITLE
BTCMarkets.prototype.publicRequest not reading params.since

### ISSUE THREAD

**Issue by davidlinder86** [naddison36/btc-markets#2]
function getOpenOrders(instrument, currency, limit, since, callback) set the variable "since" in the param list of the publicRequest:
    this.privateRequest('/order/open', callback, {
        currency: currency,
        instrument: instrument,
        limit: limit,
        since: since}
    );
But publicRequest never read this param.
As a workaround, I added this code in the publicRequest to read the "since" param in case it is set:
    // just after path declaration... Updated by myself
    if (params && params.since) {
    	path += '?since=' + params.since;
    }

**Comment by naddison36** [comment]
The BTC Markets API doco says the since parameter is passed in the body of the POST request
https://github.com/BTCMarkets/API/wiki/Trading-API#open-orders

After doing some testing, I can see the Open Orders API does ignore the since parameter. I'm not surprised by this. The open orders API just gives your open orders and is not a public API for the whole order book.

If you want your past orders you need to use getOrderHistory. I've tested and the since parameter does work for this API. Note the since parameter is the order id and not the unix timestamp.

BTW, I updated the dependencies and published version 0.0.7 on npm

**Comment by davidlinder86** [comment]
Thanks,
The same issue apply for the getTrades; the parameter "since" was not set in the param list; the small workaround of the first message made it possible to limit the trades returned using the since parameter:
BTCMarkets.prototype.getTrades = function(instrument, currency, callback, since)
{
    this.publicRequest(instrument, currency, 'trades', callback, {
        since: since}
    );
};

**Comment by naddison36** [comment]
Thanks for raising this bug. I've just published version 0.0.9 which now supports adding the since option in getTrades
